apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dwh-chat-db
  namespace: dwh-chat
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: 1
  storage:
    size: {{ .Values.database.storage.size | quote }}
    storageClass: {{ .Values.database.storage.storageClass | quote }}
  bootstrap:
    initdb:
      database: dwh_chat
      owner: dwh_chat
      secret:
        name: {{ .Values.databaseSecretName | quote }}
