{{- if .Values.cloudnativePg.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: cloudnative-pg
      repoURL: https://cloudnative-pg.io/charts/
      targetRevision: {{ .Values.cloudnativePg.version | quote }}
      helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative-pg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
