{{- if .Values.osqueryDataWarehousePrereqs.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osquery-datawarehouse-prereqs
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/osquery-datawarehouse-prereqs
    repoURL: {{ .Values.argocd.repoURL | quote }}
    targetRevision: {{ .Values.argocd.targetRevision | quote }}
    helm:
      releaseName: osquery-datawarehouse-prereqs
      valuesObject:
        namespaces:
          kafka:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
