{{- if .Values.passwordGenerator.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: password-generator
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: {{ .Values.argocd.repoURL | quote }}
      targetRevision: {{ .Values.argocd.targetRevision | quote }}
      path: charts/cluster-resources/files/password-generator
      directory:
        recurse: true
    - chart: kubernetes-secret-generator
      repoURL: https://helm.mittwald.de
      targetRevision: {{ .Values.passwordGenerator.version | quote }}
      helm:
        releaseName: password-generator
  destination:
    server: https://kubernetes.default.svc
    namespace: password-generator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
