apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-warehouse-mcp-images
  namespace: data-warehouse-mcp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
