apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: garage-admin-token
  namespace: garage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  fields:
    - fieldName: token
      length: "32"
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: token-key
  namespace: polaris
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  fields:
    - fieldName: "symmetric.key"
      encoding: "base64"
      length: "32"
---
apiVersion: v1
kind: Secret
metadata:
  name: polaris-root-credentials
  namespace: polaris
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    secret-generator.v1.mittwald.de/autogenerate: client-secret
    secret-generator.v1.mittwald.de/length: "32"
    replicator.v1.mittwald.de/replicate-to: "trino,flink"
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "trino,flink"
type: Opaque
stringData:
  realm: POLARIS
  client-id: root
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: polaris-database-app
  namespace: polaris
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: kubernetes.io/basic-auth
  data:
    username: polaris
    jdbcUrl: jdbc:postgresql://polaris-db-rw:5432/polaris
  fields:
    - fieldName: password
      length: "32"
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: dwh-chat-auth
  namespace: dwh-chat
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  fields:
    - fieldName: secret
      length: "64"
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: dwh-chat-db
  namespace: dwh-chat
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: kubernetes.io/basic-auth
  data:
    username: dwh_chat
  fields:
    - fieldName: password
      length: "32"
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: superset-secret-key
  namespace: superset
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  fields:
    - fieldName: secret-key
      encoding: base64
      length: "42"
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: superset-postgres-auth
  namespace: superset
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  fields:
    - fieldName: password
      length: "32"
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: superset-redis-auth
  namespace: superset
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  fields:
    - fieldName: password
      length: "32"
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: superset-admin-password
  namespace: superset
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  fields:
    - fieldName: password
      length: "32"
