apiVersion: v2
name: polaris
description: Apache Polaris Iceberg REST catalog
type: application
version: 0.1.0
dependencies:
  - name: polaris
    repository: https://dist.apache.org/repos/dist/release/polaris/helm-chart/
    version: "1.4.1"
    alias: polaris
